COMPONENT = SQLite
TARGET    = libsqlite3
OBJS      = sqlite3
#CDEFINES  = -DSQLITE_OS_OTHER -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_DQS=0 -DSQLITE_THREADSAFE=0 -DSQLITE_DEFAULT_MEMSTATUS=0 -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 -DSQLITE_LIKE_DOESNT_MATCH_BLOBS -DSQLITE_MAX_EXPR_DEPTH=0 -DSQLITE_OMIT_DECLTYPE -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_PROGRESS_CALLBACK -DSQLITE_OMIT_SHARED_CACHE -DSQLITE_OMIT_AUTOINIT -DSQLITE_HAVE_ISNAN -DSQLITE_MIXED_ENDIAN_64BIT_FLOAT

CDEFINES = -DRISC_OS

CINCLUDES = -IC:,OSLib:
CFLAGS   += -zpz0

include CLibrary

C_WARNINGS = -fa

# Dynamic dependencies:
